Repository tokio-rs/axum, pull requests merged in 2021-11, with the labels that each got.

#437 Rework docs
  CHANGELOG.md
  Cargo.toml
  README.md
  examples/hello-world/src/main.rs
  examples/sse/src/main.rs
  examples/static-file-server/src/main.rs
  examples/websockets/src/main.rs
  src/docs/applying_middleware.md
  src/docs/compatibility.md
  src/docs/error_handling.md
  src/docs/example.md
  src/docs/examples.md
  src/docs/extract.md
  src/docs/extractors.md
  src/docs/feature_flags.md
  src/docs/handlers.md
  src/docs/handlers_intro.md
  src/docs/high_level_features.md
  src/docs/middleware.md
  src/docs/required_dependencies.md
  src/docs/response.md
  src/docs/routing.md
  src/docs/routing/fallback.md
  src/docs/routing/into_make_service_with_connect_info.md
  src/docs/routing/layer.md
  src/docs/routing/merge.md
  src/docs/routing/nest.md
  src/docs/routing/route.md
  src/docs/sharing_state_with_handlers.md
  src/docs/table_of_contents.md
  src/error_handling/mod.rs
  src/extract/connect_info.rs
  src/extract/extractor_middleware.rs
  src/extract/mod.rs
  src/handler/mod.rs
  src/lib.rs
  src/response/mod.rs
  src/routing/future.rs
  src/routing/handler_method_routing.rs
  src/routing/into_make_service.rs
  src/routing/mod.rs
  src/routing/route.rs
  src/routing/service_method_routing.rs
  src/tests/get_to_head.rs
  src/tests/merge.rs
  src/tests/mod.rs
Labels: T-docs

#441 Clean up some todos
  src/extract/ws.rs
  src/routing/service_method_routing.rs
Labels: C-cleanup

#443 Add example showing how to handle empty vs missing query params
  examples/query-params-with-empty-strings/Cargo.toml
  examples/query-params-with-empty-strings/src/main.rs
  src/extract/query.rs
Labels: T-docs

#444 Add `Handler::{into_make_service, into_make_service_with_connect_info}`
  CHANGELOG.md
  src/extract/connect_info.rs
  src/handler/mod.rs
  src/routing/into_make_service.rs
  src/routing/mod.rs
Labels: C-enhancement

#448 Version 0.3.0
  CHANGELOG.md
Labels: T-release

#450 Add readme example project
  README.md
  examples/readme/Cargo.toml
  examples/readme/src/main.rs
Labels: T-docs

#473 Version 0.3.1
  axum/CHANGELOG.md
  axum/Cargo.toml
Labels: T-release

#474 Add `Router::route_layer`
  axum/CHANGELOG.md
  axum/src/docs/routing/route_layer.md
  axum/src/extract/extractor_middleware.rs
  axum/src/routing/mod.rs
  axum/src/routing/tests/mod.rs
Labels: C-enhancement

#483 Version 0.3.2
  axum/CHANGELOG.md
  axum/Cargo.toml
Labels: T-release

#490 Implement `IntoResponse` for `http::response::Parts`
  axum/CHANGELOG.md
  axum/src/response/mod.rs
Labels: C-enhancement

#489 Implement `FromRequest` for `http::request::Parts`
  axum/CHANGELOG.md
  axum/src/extract/rejection.rs
  axum/src/extract/request_parts.rs
Labels: C-enhancement

#503 More clearly document accepting multiple methods
  axum/src/docs/routing/route.md
  axum/src/lib.rs
Labels: T-docs

#510 axum: Version 0.3.3
  axum/CHANGELOG.md
  axum/Cargo.toml
Labels: T-release

#511 axum-debug: Version 0.2.0
  axum-debug/CHANGELOG.md
  axum-debug/Cargo.toml
Labels: T-release

#521 New method router
  axum/CHANGELOG.md
  axum/src/docs/error_handling.md
  axum/src/docs/method_routing/fallback.md
  axum/src/docs/method_routing/layer.md
  axum/src/docs/method_routing/merge.md
  axum/src/docs/method_routing/route_layer.md
  axum/src/docs/routing/nest.md
  axum/src/docs/routing/route.md
  axum/src/error_handling/mod.rs
  axum/src/handler/mod.rs
  axum/src/lib.rs
  axum/src/routing/future.rs
  axum/src/routing/method_filter.rs
  axum/src/routing/method_not_allowed.rs
  axum/src/routing/method_routing.rs
  axum/src/routing/mod.rs
  axum/src/routing/route.rs
  axum/src/routing/service_method_routing.rs
  axum/src/routing/tests/get_to_head.rs
  axum/src/routing/tests/merge.rs
  axum/src/routing/tests/mod.rs
  axum/src/routing/tests/nest.rs
  examples/sse/src/main.rs
  examples/static-file-server/src/main.rs
  examples/websockets/src/main.rs
Labels: C-enhancement, breaking change, A-axum

#532 Version 0.3.4
  axum/CHANGELOG.md
  axum/Cargo.toml
Labels: T-release

#536 Add `axum-extra` crate
  .github/workflows/CI.yml
  Cargo.toml
  axum-debug/Cargo.toml
  axum-extra/CHANGELOG.md
  axum-extra/Cargo.toml
  axum-extra/LICENSE
  axum-extra/README.md
  axum-extra/src/lib.rs
  axum/Cargo.toml
Labels: A-axum-extra

#538 Add `Resource` to axum-extra
  axum-extra/Cargo.toml
  axum-extra/src/lib.rs
  axum-extra/src/routing/mod.rs
  axum-extra/src/routing/resource.rs
Labels: A-axum-extra

#529 Panic instead of silently discarding fallbacks
  axum/CHANGELOG.md
  axum/src/docs/routing/fallback.md
  axum/src/docs/routing/merge.md
  axum/src/docs/routing/nest.md
  axum/src/routing/mod.rs
  axum/src/routing/tests/fallback.rs
  axum/src/routing/tests/mod.rs
Labels: A-axum

#518 Make `axum-debug` handle more cases
  axum-debug/CHANGELOG.md
  axum-debug/Cargo.toml
  axum-debug/src/lib.rs
  axum-debug/tests/fail/argument_not_extractor.stderr
  axum-debug/tests/fail/attrs.rs
  axum-debug/tests/fail/attrs.stderr
  axum-debug/tests/fail/extract_self_mut.rs
  axum-debug/tests/fail/extract_self_mut.stderr
  axum-debug/tests/fail/extract_self_ref.rs
  axum-debug/tests/fail/extract_self_ref.stderr
  axum-debug/tests/fail/generics.rs
  axum-debug/tests/fail/generics.stderr
  axum-debug/tests/fail/not_async.stderr
  axum-debug/tests/fail/not_send.stderr
  axum-debug/tests/fail/self_receiver.stderr
  axum-debug/tests/fail/too_many_extractors.stderr
  axum-debug/tests/fail/wrong_return_type.stderr
  axum-debug/tests/pass/associated_fn_without_self.rs
  axum-debug/tests/pass/impl_future.rs
  axum-debug/tests/pass/impl_into_response.rs
  axum-debug/tests/pass/mut_extractor.rs
  axum-debug/tests/pass/ready.rs
  axum-debug/tests/pass/returns_self.rs
  axum-debug/tests/pass/self_receiver.rs
Labels: C-enhancement, A-axum-debug

#545 axum-debug: Version 0.2.1
  axum-debug/CHANGELOG.md
  axum-debug/Cargo.toml
Labels: T-release

#544 Change how `Resource`s are added to `Router`s
  axum-extra/src/routing/mod.rs
  axum-extra/src/routing/resource.rs
Labels: A-axum-extra

#552 Fix `#[debug_handler]` for multiple extractors
  axum-debug/CHANGELOG.md
  axum-debug/src/lib.rs
  axum-debug/tests/pass/multiple_extractors.rs
Labels: A-axum-debug

#553 axum-debug: Version 0.2.2
  axum-debug/CHANGELOG.md
  axum-debug/Cargo.toml
Labels: T-release

#565 Add `Cached` extractor
  axum-extra/Cargo.toml
  axum-extra/src/extract/cached.rs
  axum-extra/src/extract/mod.rs
  axum-extra/src/lib.rs
  axum/src/macros.rs
Labels: A-axum-extra
