Repository tokio-rs/axum, pull requests merged in 2021-10, with the labels that each got.

#359 Add `Customizing extractor responses` section to docs
  src/lib.rs
Labels: T-docs

#360 Version 0.2.6
  CHANGELOG.md
  Cargo.toml
Labels: T-release

#339 Improve performance of `BoxRoute`
  CHANGELOG.md
  src/buffer.rs
  src/clone_box_service.rs
  src/lib.rs
  src/routing/future.rs
  src/routing/mod.rs
Labels: C-enhancement, breaking change

#286 Make JSON and HTTP1 support optional
  Cargo.toml
  src/extract/mod.rs
  src/extract/rejection.rs
  src/json.rs
  src/lib.rs
  src/response/mod.rs
  src/response/sse.rs
Labels: C-enhancement, breaking change

#272 Percent decode automatically in `extract::Path`
  CHANGELOG.md
  Cargo.toml
  src/extract/path/de.rs
  src/extract/path/mod.rs
  src/extract/rejection.rs
  src/routing/mod.rs
  src/util.rs
Labels: C-enhancement, breaking change

#371 Version 0.2.7
  CHANGELOG.md
  Cargo.toml
Labels: T-release

#376 Remove some `#[allow(warnings)]`
  src/extract/form.rs
  src/extract/path/mod.rs
  src/routing/future.rs
  src/routing/or.rs
  src/service/future.rs
Labels: C-cleanup

#432 Break root module docs into separate files
  .github/workflows/CI.yml
  README.md
  src/docs/applying_middleware.md
  src/docs/building_responses.md
  src/docs/compatibility.md
  src/docs/error_handling.md
  src/docs/example.md
  src/docs/examples.md
  src/docs/extractors.md
  src/docs/feature_flags.md
  src/docs/handlers.md
  src/docs/high_level_features.md
  src/docs/required_dependencies.md
  src/docs/routing.md
  src/docs/sharing_state_with_handlers.md
  src/docs/table_of_contents.md
  src/lib.rs
Labels: T-docs
