Repository tokio-rs/axum, pull requests merged in 2021-08, with the labels that each got.

#69 Clarify required response body type when routing to `tower::Service`s
  CHANGELOG.md
  src/body.rs
  src/lib.rs
Labels: T-docs

#71 Improve documentation for router
  CHANGELOG.md
  src/lib.rs
Labels: T-docs

#72 Improve error message of `MissingExtension` rejections
  CHANGELOG.md
  src/extract/mod.rs
  src/extract/rejection.rs
Labels: C-enhancement

#74 Fix docs in service/mod.rs
  src/service/mod.rs
Labels: T-docs

#77 Mention required dependencies in docs
  CHANGELOG.md
  src/lib.rs
Labels: T-docs

#79 Including tracing setup in all examples
  README.md
  examples/error_handling_and_dependency_injection.rs
  examples/form.rs
  examples/hello_world.rs
  examples/sessions.rs
  examples/templates.rs
  examples/tls_rustls.rs
  examples/tokio_postgres.rs
  examples/unix_domain_socket.rs
  examples/versioning.rs
Labels: T-docs

#80 Version 0.1.2
  CHANGELOG.md
  Cargo.toml
  src/lib.rs
Labels: T-release

#92 Make it clear how to run all examples
  Cargo.toml
  examples/chat.rs
  examples/error_handling_and_dependency_injection.rs
  examples/form.rs
  examples/hello_world.rs
  examples/key_value_store.rs
  examples/multipart_form.rs
  examples/sessions.rs
  examples/sse.rs
  examples/static_file_server.rs
  examples/templates.rs
  examples/testing.rs
  examples/tls_rustls.rs
  examples/todos.rs
  examples/tokio_postgres.rs
  examples/unix_domain_socket.rs
  examples/versioning.rs
  examples/websocket.rs
Labels: T-docs

#118 Replace `hyper::Server` with `axum::Server` in docs
  README.md
  examples/404.rs
  examples/async-graphql/main.rs
  examples/chat.rs
  examples/error_handling_and_dependency_injection.rs
  examples/form.rs
  examples/hello_world.rs
  examples/key_value_store.rs
  examples/multipart_form.rs
  examples/sessions.rs
  examples/sse.rs
  examples/static_file_server.rs
  examples/templates.rs
  examples/testing.rs
  examples/todos.rs
  examples/tokio_postgres.rs
  examples/unix_domain_socket.rs
  examples/versioning.rs
  examples/websocket.rs
  src/extract/connect_info.rs
  src/extract/content_length_limit.rs
  src/extract/extension.rs
  src/extract/extractor_middleware.rs
  src/extract/form.rs
  src/extract/json.rs
  src/extract/mod.rs
  src/extract/multipart.rs
  src/extract/query.rs
  src/extract/raw_query.rs
  src/extract/request_parts.rs
  src/extract/typed_header.rs
  src/extract/url_params.rs
  src/extract/url_params_map.rs
  src/handler/mod.rs
  src/lib.rs
  src/routing.rs
  src/service/mod.rs
  src/sse.rs
  src/ws/mod.rs
Labels: T-docs

#123 Set RUST_LOG environment var for all examples using tracing
  examples/404.rs
  examples/error_handling_and_dependency_injection.rs
  examples/form.rs
  examples/hello_world.rs
  examples/key_value_store.rs
  examples/multipart_form.rs
  examples/sessions.rs
  examples/sse.rs
  examples/static_file_server.rs
  examples/templates.rs
  examples/testing.rs
  examples/tls_rustls.rs
  examples/todos.rs
  examples/tokio_postgres.rs
  examples/unix_domain_socket.rs
  examples/versioning.rs
  examples/websocket.rs
Labels: T-docs

#130 Move response futures into their own modules
  src/extract/extractor_middleware.rs
  src/routing.rs
  src/routing/future.rs
  src/service/future.rs
  src/service/mod.rs
Labels: C-cleanup

#131 Handle `METHOD_NOT_ALLOWED` in 404 example
  examples/404.rs
Labels: C-enhancement, C-cleanup

#124 Implement path extractor.
  CHANGELOG.md
  examples/error_handling_and_dependency_injection.rs
  examples/key_value_store.rs
  examples/templates.rs
  examples/todos.rs
  examples/versioning.rs
  src/extract/mod.rs
  src/extract/path/de.rs
  src/extract/path/mod.rs
  src/extract/rejection.rs
  src/lib.rs
  src/tests.rs
  src/tests/nest.rs
  src/util.rs
Labels: C-enhancement

#139 Version 0.1.3
  CHANGELOG.md
  Cargo.toml
  src/lib.rs
Labels: T-release

#146 Make `FromRequest` default to use `axum::body::Body`
  CHANGELOG.md
  src/body.rs
  src/extract/mod.rs
Labels: C-enhancement

#140 Common JSON wrapper type for response and request.
  src/extract/json.rs
  src/extract/mod.rs
  src/json.rs
  src/lib.rs
  src/macros.rs
  src/response.rs
Labels: C-cleanup, breaking change

#132 Remove `Copy` some impls
  CHANGELOG.md
  src/extract/extractor_middleware.rs
  src/routing.rs
Labels: C-cleanup, breaking change

#133 Remove future re-exports
  CHANGELOG.md
  src/extract/extractor_middleware.rs
  src/handler/mod.rs
  src/routing.rs
  src/service/mod.rs
Labels: C-cleanup, breaking change

#125 Remove `QueryStringMissing` as it was no longer being used
  CHANGELOG.md
  src/extract/rejection.rs
Labels: C-cleanup, breaking change

#120 Fix `ServiceExt::handle_error` footgun
  CHANGELOG.md
  src/handler/mod.rs
  src/routing.rs
  src/service/mod.rs
Labels: C-enhancement, breaking change

#108 Add `RouteDsl::or` to combine routes
  CHANGELOG.md
  src/lib.rs
  src/routing.rs
  src/routing/or.rs
  src/tests.rs
  src/tests/or.rs
Labels: breaking change

#121 Change WebSocket API to use an extractor
  CHANGELOG.md
  examples/chat.rs
  examples/websocket.rs
  src/extract/mod.rs
  src/extract/ws.rs
  src/lib.rs
  src/ws/future.rs
  src/ws/mod.rs
Labels: C-enhancement, breaking change

#86 Support returning any `http_body::Body` from `IntoResponse`
  CHANGELOG.md
  examples/error_handling_and_dependency_injection.rs
  examples/templates.rs
  examples/versioning.rs
  src/extract/content_length_limit.rs
  src/extract/rejection.rs
  src/extract/tuple.rs
  src/extract/ws.rs
  src/handler/mod.rs
  src/json.rs
  src/lib.rs
  src/macros.rs
  src/response.rs
Labels: C-enhancement, breaking change

#116 Make ws::Message an enum for easier frame type matching
  CHANGELOG.md
  examples/chat.rs
  examples/websocket.rs
  src/extract/ws.rs
Labels: C-enhancement, breaking change

#150 Add `axum::Error`
  CHANGELOG.md
  src/body.rs
  src/error.rs
  src/extract/form.rs
  src/extract/rejection.rs
  src/extract/request_parts.rs
  src/extract/ws.rs
  src/json.rs
  src/lib.rs
  src/macros.rs
  src/response.rs
  src/sse.rs
Labels: breaking change

#151 Remove `take_*` methods from RequestParts for Version, Method, and Uri
  CHANGELOG.md
  src/extract/form.rs
  src/extract/mod.rs
  src/extract/query.rs
  src/extract/raw_query.rs
  src/extract/rejection.rs
  src/extract/request_parts.rs
  src/extract/ws.rs
Labels: C-enhancement, breaking change

#152 Re-export `http_body::Body`
  src/body.rs
  src/response.rs
Labels: C-enhancement

#153 Implement `std::error::Error` for all rejections
  CHANGELOG.md
  src/extract/rejection.rs
  src/macros.rs
Labels: C-enhancement

#154 Remove `UrlParamsMap` and `UrlParams`
  CHANGELOG.md
  src/extract/mod.rs
  src/extract/rejection.rs
  src/extract/url_params.rs
  src/extract/url_params_map.rs
  src/routing.rs
Labels: C-cleanup

#156 Fix `Uri` extractor not being the full URI if using `nest`
  CHANGELOG.md
  src/extract/mod.rs
  src/routing.rs
  src/tests/nest.rs
Labels: C-enhancement

#155 Add dedicated tracing/logging example
  examples/README.md
  examples/tracing_aka_logging.rs
Labels: T-docs

#157 Add unique future types for all services
  CHANGELOG.md
  src/handler/future.rs
  src/handler/mod.rs
  src/routing.rs
  src/routing/future.rs
  src/service/future.rs
  src/service/mod.rs
Labels: C-enhancement

#158 Implement `MethodFilter` via bitflags
  CHANGELOG.md
  Cargo.toml
  src/handler/mod.rs
  src/routing.rs
  src/routing/method_filter.rs
  src/service/mod.rs
  src/tests.rs
Labels: C-enhancement

#160 Move methods from `ServiceExt` to `RoutingDsl`
  CHANGELOG.md
  examples/key_value_store.rs
  examples/sse.rs
  examples/static_file_server.rs
  examples/todos.rs
  examples/websocket.rs
  src/handler/mod.rs
  src/lib.rs
  src/routing.rs
  src/service/mod.rs
  src/tests.rs
  src/tests/handle_error.rs
Labels: C-enhancement

#161 Add `NestedUri`
  CHANGELOG.md
  src/extract/mod.rs
  src/extract/rejection.rs
  src/extract/request_parts.rs
  src/routing.rs
  src/tests/nest.rs
Labels: C-enhancement

#162 Re-export more body utilities
  src/body.rs
  src/extract/request_parts.rs
  src/response.rs
Labels: C-enhancement

#144 Add oauth2 example
  Cargo.toml
  examples/README.md
  examples/oauth.rs
Labels: T-docs

#167 Clean up `RequestParts` API
  CHANGELOG.md
  Cargo.toml
  src/error.rs
  src/extract/extractor_middleware.rs
  src/extract/mod.rs
  src/extract/rejection.rs
  src/extract/request_parts.rs
  src/tests/mod.rs
Labels: C-cleanup

#169 Implement `FromRequest` for `http::Extensions`
  CHANGELOG.md
  src/extract/request_parts.rs
Labels: C-enhancement

#98 Implement SSE using responses
  CHANGELOG.md
  Cargo.toml
  examples/sse.rs
  src/lib.rs
  src/response/mod.rs
  src/response/sse.rs
  src/sse.rs
Labels: C-enhancement, breaking change

#129 Correctly handle HEAD requests
  CHANGELOG.md
  Cargo.toml
  examples/tokio_postgres.rs
  src/handler/future.rs
  src/handler/mod.rs
  src/service/future.rs
  src/service/mod.rs
  src/tests/get_to_head.rs
  src/tests/mod.rs
Labels: C-enhancement, breaking change

#189 Refactor `TypedHeader` extractor
  src/extract/rejection.rs
  src/extract/typed_header.rs
  src/service/mod.rs
  src/tests/get_to_head.rs
  src/tests/mod.rs
Labels: C-cleanup

#175 docs: move relevant sections to be under "Routing"
  src/lib.rs
Labels: T-docs

#190 Remove one allocation when calling handler
  src/handler/future.rs
  src/handler/mod.rs
Labels: C-cleanup

#192 Add `Redirect` response
  CHANGELOG.md
  examples/oauth.rs
  src/response/mod.rs
  src/response/redirect.rs
Labels: C-enhancement

#194 Make `RequestParts::{new, try_into_request}` public
  CHANGELOG.md
  src/extract/mod.rs
Labels: C-enhancement

#193 Add `Headers`
  .clippy.toml
  CHANGELOG.md
  src/response/headers.rs
  src/response/mod.rs
Labels: C-enhancement

#199 Work around for http2 hang with `Or`
  examples/hello_world.rs
  src/routing/mod.rs
  src/routing/or.rs
  src/tests/or.rs
Labels: C-enhancement

#198 Improve compile times of `handle_error` and `check_infallible`
  CHANGELOG.md
  src/routing/mod.rs
  src/service/mod.rs
Labels: C-enhancement

#212 Bring back `Handler::into_service`
  src/handler/future.rs
  src/handler/into_service.rs
  src/handler/mod.rs
  src/tests/mod.rs
Labels: C-enhancement

#214 Replace `RoutingDsl` trait with `Router` type
  CHANGELOG.md
  examples/async-graphql/src/main.rs
  examples/chat/src/main.rs
  examples/error-handling-and-dependency-injection/src/main.rs
  examples/form/src/main.rs
  examples/global-404-handler/src/main.rs
  examples/hello-world/src/main.rs
  examples/key-value-store/src/main.rs
  examples/multipart-form/src/main.rs
  examples/oauth/src/main.rs
  examples/sessions/src/main.rs
  examples/sse/src/main.rs
  examples/static-file-server/src/main.rs
  examples/templates/src/main.rs
  examples/testing/src/main.rs
  examples/todos/src/main.rs
  examples/tokio-postgres/src/main.rs
  examples/tracing-aka-logging/src/main.rs
  examples/unix-domain-socket/src/main.rs
  examples/versioning/src/main.rs
  examples/websockets/src/main.rs
  src/extract/connect_info.rs
  src/extract/content_length_limit.rs
  src/extract/extension.rs
  src/extract/extractor_middleware.rs
  src/extract/form.rs
  src/extract/mod.rs
  src/extract/multipart.rs
  src/extract/path/mod.rs
  src/extract/query.rs
  src/extract/raw_query.rs
  src/extract/request_parts.rs
  src/extract/typed_header.rs
  src/extract/ws.rs
  src/handler/mod.rs
  src/json.rs
  src/lib.rs
  src/response/headers.rs
  src/response/mod.rs
  src/response/redirect.rs
  src/response/sse.rs
  src/routing/mod.rs
  src/routing/or.rs
  src/service/mod.rs
  src/tests/mod.rs
Labels: C-cleanup

#215 Replace `route` with `Router::new().route()`
  CHANGELOG.md
  examples/async-graphql/src/main.rs
  examples/chat/src/main.rs
  examples/error-handling-and-dependency-injection/src/main.rs
  examples/form/src/main.rs
  examples/global-404-handler/src/main.rs
  examples/hello-world/src/main.rs
  examples/key-value-store/src/main.rs
  examples/multipart-form/src/main.rs
  examples/oauth/src/main.rs
  examples/sessions/src/main.rs
  examples/sse/src/main.rs
  examples/static-file-server/src/main.rs
  examples/templates/src/main.rs
  examples/testing/src/main.rs
  examples/tls-rustls/src/main.rs
  examples/todos/src/main.rs
  examples/tokio-postgres/src/main.rs
  examples/tracing-aka-logging/src/main.rs
  examples/unix-domain-socket/src/main.rs
  examples/versioning/src/main.rs
  examples/websockets/src/main.rs
  src/extract/connect_info.rs
  src/extract/content_length_limit.rs
  src/extract/extension.rs
  src/extract/extractor_middleware.rs
  src/extract/form.rs
  src/extract/mod.rs
  src/extract/multipart.rs
  src/extract/path/mod.rs
  src/extract/query.rs
  src/extract/raw_query.rs
  src/extract/request_parts.rs
  src/extract/typed_header.rs
  src/extract/ws.rs
  src/handler/mod.rs
  src/json.rs
  src/lib.rs
  src/response/headers.rs
  src/response/mod.rs
  src/response/redirect.rs
  src/response/sse.rs
  src/routing/mod.rs
  src/service/mod.rs
  src/tests/get_to_head.rs
  src/tests/handle_error.rs
  src/tests/mod.rs
  src/tests/nest.rs
  src/tests/or.rs
Labels: C-cleanup

#216 Add `print-request-response` example
  examples/print-request-response/Cargo.toml
  examples/print-request-response/src/main.rs
Labels: T-docs

#220 Further compile time improvements
  src/routing/mod.rs
  src/tests/handle_error.rs
Labels: C-enhancement

#221 Simplify handler trait
  src/handler/future.rs
  src/handler/into_service.rs
  src/handler/mod.rs
  src/tests/handle_error.rs
Labels: C-cleanup

#222 Add more examples to "Building responses" section
  src/lib.rs
Labels: T-docs

#224 Fallback to calling next route if no methods match
  CHANGELOG.md
  src/lib.rs
  src/routing/future.rs
  src/routing/mod.rs
  src/routing/or.rs
  src/tests/mod.rs
Labels: C-enhancement

#226 Fix 404 example
  examples/global-404-handler/src/main.rs
Labels: T-docs

#228 Mention using `Path<HashMap>` to capture all params
  src/extract/path/mod.rs
Labels: T-docs

#230 Fix `nest` docs inconsistency
  src/lib.rs
  src/routing/mod.rs
Labels: T-docs

#232 Document not being able to mix fallible and infallible routes
  src/lib.rs
Labels: T-docs

#238 Group items in changelog differently
  CHANGELOG.md
Labels: T-docs

#237 Add `StreamBody`
  CHANGELOG.md
  src/body.rs
  src/body/stream_body.rs
  src/response/mod.rs
  src/tests/mod.rs
Labels: C-enhancement

#239 Expand middleware docs
  src/lib.rs
Labels: T-docs

#241 Remove boxing from `StreamBody`
  CHANGELOG.md
  src/body/stream_body.rs
  src/extract/request_parts.rs
  src/response/mod.rs
Labels: C-enhancement

#245 Add upgrade examples to the changelog
  CHANGELOG.md
  README.md
Labels: T-docs

#247 Version 0.2.0
  CHANGELOG.md
  Cargo.toml
Labels: T-release

#254 Simplify tls-rustls example
  examples/low-level-rustls/Cargo.toml
  examples/low-level-rustls/self_signed_certs/cert.pem
  examples/low-level-rustls/self_signed_certs/key.pem
  examples/low-level-rustls/src/main.rs
  examples/tls-rustls/Cargo.toml
  examples/tls-rustls/src/main.rs
Labels: T-docs

#258 Document how to implement `IntoResponse` for custom error type
  CHANGELOG.md
  src/response/mod.rs
Labels: T-docs

#256 Version 0.2.1
  CHANGELOG.md
  Cargo.toml
Labels: T-release

#264 Fix URI captures matching empty segments
  CHANGELOG.md
  src/routing/mod.rs
  src/tests/mod.rs
Labels: C-enhancement

#291 Document using `StreamExt::split` with `WebSocket`
  src/extract/ws.rs
Labels: T-docs

#293 Document adding middleware to multiple groups of routes
  src/lib.rs
Labels: T-docs

#294 Remove repeated constraint
  src/handler/mod.rs
Labels: C-cleanup
